#!/bin/bash 

echo "Let's deploy a bare-metal cluster on GCP"

echo "First we will initialize gcloud and connect to our project"
gcloud init
gcloud auth login
gcloud projects list

gcloud compute instances list

echo "Create the K8s Cluster"
echo "1 master and 1 worker | e2-medium | Ubuntu 20.04 LTS"

# CREATE cks-master VM using gcloud command
# not necessary if created using the browser interface
gcloud compute instances create cks-master --zone=europe-west3-c \
--machine-type=e2-medium \
--image=ubuntu-2004-focal-v20220419 \
--image-project=ubuntu-os-cloud \
--boot-disk-size=50GB

# CREATE cks-worker VM using gcloud command
# not necessary if created using the browser interface
gcloud compute instances create cks-worker --zone=europe-west3-c \
--machine-type=e2-medium \
--image=ubuntu-2004-focal-v20220419 \
--image-project=ubuntu-os-cloud \
--boot-disk-size=50GB


gcloud config set compute/zone us-east1-b
gcloud compute ssh master
sudo -i
#install kubeadm in cluster
#Copy the kubeadm join command an paste it after running the second script in the worker node 

gcloud compute ssh worker
sudo -i
#run kubeadm scripts in the worker

#open firewall ports to use nodeports 
gcloud compute firewall-rules create nodeport --allow tcp:30000-40000