apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: flask
  name: flask-svc
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    run: flask-app
  type: NodePort
status:
  loadBalancer: {}